### ISSUE TITLE
MySql Conector

### ISSUE THREAD

**Issue by Priyankadas16** [unchartedsoftware/influent#5] opened 2015-04-21 18:29 UTC
Hi , I am trying to add mysql connector in pom.xml to connect to mysql repository by adding 
<dependency>
<groupId>mysql</groupId>
<artifactId>mysql-connector-java</artifactId>
<version>5.1.6</version>
</dependency>

but its not working.
Any Suggestion.

**Comment by dgauldie** [comment] 2015-04-21 18:54
You will also want to replace the database server properties in the app properties file. with the following:

```
influent.midtier.database.type = mysql
influent.midtier.database.url = jdbc:mysql://myDatabaseLocation:3306/mySqlDatabaseName
influent.midtier.database.driver = com.mysql.jdbc.Driver
influent.midtier.user.name = myUsername
influent.midtier.user.password = myPassword
```

**Comment by Priyankadas16** [comment] 2015-04-22 00:54
I have made the same changes , but it says No suitable driver found for
jdbc:mysql://localhost:3306/kiva
 i have also made changes in pom.xml

<dependency>

 <groupId>mysql</groupId>

 <artifactId>mysql-connector-java</artifactId>

 <version>5.1.6</version>

</dependency>


 but still same issue.


Regards

Priyanka

**Comment by Priyankadas16** [comment] 2015-04-22 01:49
And also when trying to run with hsqldb connector , it give below exception

org.hsqldb.HsqlException: Client driver version greater than
'-268.-50.-11.-74' is required.  HSQLDB server version is '2.3.2'

at org.hsqldb.error.Error.error(Unknown Source)

at org.hsqldb.server.ServerConnection.init(Unknown Source)

at org.hsqldb.server.ServerConnection.run(Unknown Source)

at java.lang.Thread.run(Thread.java:745)

**Comment by Priyankadas16** [comment] 2015-04-22 19:25
Hi Team,

please help on version disambiguation in hsqldb.I checked in all the files,
but unable to find the issue,

Thanks in advance

Priyanka

**Comment by jamespr** [comment] 2015-04-22 19:36
Ensure the version of the HSQLDB jar you're using matches what the server
or db file is requesting (2.3.2).

The correct version of HSQLDB for the Kiva demo data is in a switch in the
Kiva pom.xml. You can enable by setting -Dinfluent.dataaccess.hsqldb=true
in your build step.

**Comment by dgauldie** [comment] 2015-04-22 19:37
Hi Priyanka,

Which pom file did you place the the mysql dependency in?

**Comment by Priyankadas16** [comment] 2015-04-23 02:48
i have placed in pom.xml of kiva

Regards
Priyanka

**Comment by Priyankadas16** [comment] 2015-04-26 11:45
Hi, team

I am Still facing same problem with mysql connector .

Any Suggestion?

Regards
Priyanka

**Comment by jamespr** [comment] 2015-04-26 16:01
Hi Priyanka,

Could you paste the relevant influent.midtier lines from your app.properties file? And also the mysql dependency lines from your pom?

I'll take a look to see if I can see where the issue is.

Thanks,
James

**Comment by Priyankadas16** [comment] 2015-04-27 06:10
Hi James,

Thankx for reply, here is my influent.midtier lines:

influent.midtier.database.type = mysql

influent.midtier.database.url = jdbc:mysql://localhost:3306/kiva

influent.midtier.database.driver = com.mysql.jdbc.Driver

influent.midtier.user.name = root

influent.midtier.user.password =root


influent.midtier.solr.url = http://localhost:8983/solr/demoKivaSolr


and mysql dependency added in pom.xml of kiva:


<dependency>

 <groupId>mysql</groupId>

 <artifactId>mysql-connector-java</artifactId>

 <version>5.1.6</version>

</dependency>


Regards


Priyanka

**Comment by jamespr** [comment] 2015-04-27 17:27
Hi Priyanka,

I just tested Influent 1.3.6 with your settings and it connects to my MySQL database containing Kiva demo data. I am then able to use Influent with this data.

Did you try doing a full clean maven build after changing your pom files?

If you continue to get the error message, can you paste the exact error(s) here?

Thanks,
James

**Comment by Priyankadas16** [comment] 2015-04-27 18:09
Hi,

I am using influent 2.0.0 with the same configuration, and after doing mvn
clean install for influent and mvn package jetty:run for kiva i am getting
following error:

[INFO] Restart completed at Mon Apr 27 23:34:01 IST 2015

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(
SelfFirstStrategy.java:50)

at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(
ClassRealm.java:244)

at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(
ClassRealm.java:230)

at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(
WebAppClassLoader.java:428)

at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(
WebAppClassLoader.java:381)

at java.lang.Class.forName0(Native Method)

at java.lang.Class.forName(Class.java:260)

at influent.server.utilities.BoneCPConnectionPool.getConnection(
BoneCPConnectionPool.java:126)

at influent.server.utilities.BoneCPConnectionPool.<init>(
BoneCPConnectionPool.java:85)

at influent.server.spi.SQLConnectionPoolModule.connect(
SQLConnectionPoolModule.java:84)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(
NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(
DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)

at com.google.inject.internal.InternalFactoryToProviderAdapter.get(
InternalFactoryToProviderAdapter.java:40)

at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(
ProviderToInternalFactoryAdapter.java:46)

at com.google.inject.internal.InjectorImpl.callInContext(
InjectorImpl.java:1031)

at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(
ProviderToInternalFactoryAdapter.java:40)

at com.google.inject.Scopes$1$1.get(Scopes.java:65)

at com.google.inject.internal.InternalFactoryToProviderAdapter.get(
InternalFactoryToProviderAdapter.java:40)

at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)

at com.google.inject.internal.InjectorImpl.callInContext(
InjectorImpl.java:1031)

at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)

at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:89)

at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:98)

at com.google.inject.internal.InternalFactoryToProviderAdapter.get(
InternalFactoryToProviderAdapter.java:40)

at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(
ProviderToInternalFactoryAdapter.java:46)

at com.google.inject.internal.InjectorImpl.callInContext(
InjectorImpl.java:1031)

at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(
ProviderToInternalFactoryAdapter.java:40)

at com.google.inject.Scopes$1$1.get(Scopes.java:65)

at com.google.inject.internal.InternalFactoryToProviderAdapter.get(
InternalFactoryToProviderAdapter.java:40)

at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)

at com.google.inject.internal.SingleParameterInjector.inject(
SingleParameterInjector.java:38)

at com.google.inject.internal.SingleParameterInjector.getAll(
SingleParameterInjector.java:62)

at com.google.inject.internal.ConstructorInjector.construct(
ConstructorInjector.java:84)

at com.google.inject.internal.ConstructorBindingImpl$Factory.get(
ConstructorBindingImpl.java:254)

at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)

at com.google.inject.internal.InjectorImpl.callInContext(
InjectorImpl.java:1024)

at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)

at com.google.inject.internal.InjectorImpl.getInstance(
InjectorImpl.java:1013)

at oculus.aperture.rest.GuiceFinderFactory$MyFinder.create(
GuiceFinderFactory.java:65)

at org.restlet.resource.Finder.find(Finder.java:203)

at org.restlet.resource.Finder.handle(Finder.java:229)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Router.doHandle(Router.java:431)

at org.restlet.routing.Router.handle(Router.java:648)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.engine.application.StatusFilter.doHandle(
StatusFilter.java:155)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)

at org.restlet.engine.application.ApplicationHelper.handle(
ApplicationHelper.java:84)

at org.restlet.Application.handle(Application.java:381)

at org.restlet.ext.servlet.ServletAdapter.service(ServletAdapter.java:206)

at oculus.aperture.rest.RestletServlet.service(RestletServlet.java:75)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

at com.google.inject.servlet.ServletDefinition.doService(
ServletDefinition.java:263)

at com.google.inject.servlet.ServletDefinition.service(
ServletDefinition.java:178)

at com.google.inject.servlet.ManagedServletPipeline.service(
ManagedServletPipeline.java:91)

at com.google.inject.servlet.FilterChainInvocation.doFilter(
FilterChainInvocation.java:62)

at oculus.aperture.rest.RestModule$CustomPageCachingFilter.doFilter(
RestModule.java:159)

at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)

at com.google.inject.servlet.FilterDefinition.doFilter(
FilterDefinition.java:163)

at com.google.inject.servlet.FilterChainInvocation.doFilter(
FilterChainInvocation.java:58)

at com.google.inject.servlet.ManagedFilterPipeline.dispatch(
ManagedFilterPipeline.java:118)

at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)

at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(
ServletHandler.java:1322)

at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473
)

at org.eclipse.jetty.server.handler.ScopedHandler.handle(
ScopedHandler.java:119)

at org.eclipse.jetty.security.SecurityHandler.handle(
SecurityHandler.java:514)

at org.eclipse.jetty.server.session.SessionHandler.doHandle(
SessionHandler.java:226)

at org.eclipse.jetty.server.handler.ContextHandler.doHandle(
ContextHandler.java:920)

at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)

at org.eclipse.jetty.server.session.SessionHandler.doScope(
SessionHandler.java:184)

at org.eclipse.jetty.server.handler.ContextHandler.doScope(
ContextHandler.java:856)

at org.eclipse.jetty.server.handler.ScopedHandler.handle(
ScopedHandler.java:117)

at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(
ContextHandlerCollection.java:247)

at org.eclipse.jetty.server.handler.HandlerCollection.handle(
HandlerCollection.java:151)

at org.eclipse.jetty.server.handler.HandlerWrapper.handle(
HandlerWrapper.java:114)

at org.eclipse.jetty.server.Server.handle(Server.java:352)

at org.eclipse.jetty.server.HttpConnection.handleRequest(
HttpConnection.java:596)

at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(
HttpConnection.java:1066)

at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)

at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)

at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)

at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(
SelectChannelEndPoint.java:510)

at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(
SelectChannelEndPoint.java:34)

at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(
SelectChannelEndPoint.java:40)

at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(
QueuedThreadPool.java:450)

at java.lang.Thread.run(Thread.java:745)

Error while retrieving summary from data source

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(
SelfFirstStrategy.java:50)

at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(
ClassRealm.java:244)

at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(
ClassRealm.java:230)

at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(
WebAppClassLoader.java:428)

at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(
WebAppClassLoader.java:381)

at java.lang.Class.forName0(Native Method)

at java.lang.Class.forName(Class.java:260)

at influent.server.utilities.BoneCPConnectionPool.getConnection(
BoneCPConnectionPool.java:126)

at influent.server.dataaccess.DataViewDataAccess.getDataSummary(
DataViewDataAccess.java:463)

at influent.server.rest.DataSummaryResource.getDataSummary(
DataSummaryResource.java:71)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(
NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(
DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at org.restlet.resource.ServerResource.doHandle(ServerResource.java:503)

at org.restlet.resource.ServerResource.post(ServerResource.java:1216)

at org.restlet.resource.ServerResource.doHandle(ServerResource.java:592)

at org.restlet.resource.ServerResource.doNegotiatedHandle(
ServerResource.java:649)

at org.restlet.resource.ServerResource.doConditionalHandle(
ServerResource.java:348)

at org.restlet.resource.ServerResource.handle(ServerResource.java:952)

at org.restlet.resource.Finder.handle(Finder.java:246)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Router.doHandle(Router.java:431)

at org.restlet.routing.Router.handle(Router.java:648)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.engine.application.StatusFilter.doHandle(
StatusFilter.java:155)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.routing.Filter.doHandle(Filter.java:159)

at org.restlet.routing.Filter.handle(Filter.java:206)

at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)

at org.restlet.engine.application.ApplicationHelper.handle(
ApplicationHelper.java:84)

at org.restlet.Application.handle(Application.java:381)

at org.restlet.ext.servlet.ServletAdapter.service(ServletAdapter.java:206)

at oculus.aperture.rest.RestletServlet.service(RestletServlet.java:75)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

at com.google.inject.servlet.ServletDefinition.doService(
ServletDefinition.java:263)

at com.google.inject.servlet.ServletDefinition.service(
ServletDefinition.java:178)

at com.google.inject.servlet.ManagedServletPipeline.service(
ManagedServletPipeline.java:91)

at com.google.inject.servlet.FilterChainInvocation.doFilter(
FilterChainInvocation.java:62)

at oculus.aperture.rest.RestModule$CustomPageCachingFilter.doFilter(
RestModule.java:159)

at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)

at com.google.inject.servlet.FilterDefinition.doFilter(
FilterDefinition.java:163)

at com.google.inject.servlet.FilterChainInvocation.doFilter(
FilterChainInvocation.java:58)

at com.google.inject.servlet.ManagedFilterPipeline.dispatch(
ManagedFilterPipeline.java:118)

at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)

at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(
ServletHandler.java:1322)

at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473
)

at org.eclipse.jetty.server.handler.ScopedHandler.handle(
ScopedHandler.java:119)

at org.eclipse.jetty.security.SecurityHandler.handle(
SecurityHandler.java:514)

at org.eclipse.jetty.server.session.SessionHandler.doHandle(
SessionHandler.java:226)

at org.eclipse.jetty.server.handler.ContextHandler.doHandle(
ContextHandler.java:920)

at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)

at org.eclipse.jetty.server.session.SessionHandler.doScope(
SessionHandler.java:184)

at org.eclipse.jetty.server.handler.ContextHandler.doScope(
ContextHandler.java:856)

at org.eclipse.jetty.server.handler.ScopedHandler.handle(
ScopedHandler.java:117)

at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(
ContextHandlerCollection.java:247)

at org.eclipse.jetty.server.handler.HandlerCollection.handle(
HandlerCollection.java:151)

at org.eclipse.jetty.server.handler.HandlerWrapper.handle(
HandlerWrapper.java:114)

at org.eclipse.jetty.server.Server.handle(Server.java:352)

at org.eclipse.jetty.server.HttpConnection.handleRequest(
HttpConnection.java:596)

at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(
HttpConnection.java:1066)

at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)

at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)

at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)

at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(
SelectChannelEndPoint.java:510)

at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(
SelectChannelEndPoint.java:34)

at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(
SelectChannelEndPoint.java:40)

at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(
QueuedThreadPool.java:450)

at java.lang.Thread.run(Thread.java:745)

Regards
Priyanka

**Comment by jamespr** [comment] 2015-04-27 18:58
Hi Priyanka,

Your settings also work for me in 2.0.0-beta.

I can reproduce your error if I remove the mysql dependency from the pom.xml; meaning you are getting that error because it cannot find the mysql-connector-java-5.1.6.jar file in the class path.

1) Ensure that mysql-connector-java-5.1.6.jar is in the lib folder for your generated target (e.g kiva\target\kiva-2.0.0-SNAPSHOT\WEB-INF\lib). If it is there, then the application cannot find it on the classpath.
2) Try building the Walker example application instead. Change the database.url to:

`influent.midtier.database.url = jdbc:mysql://solr.uncharted.software:3306/walker`


This is already set up for mysql, with the appropriate pom settings.

--J

**Comment by Priyankadas16** [comment] 2015-04-27 19:41
Hi ,

i tried again, and this i got caught with some another script exception i.e


   1. [error] Script error. :0
   2. [error] Error: Mismatched anonymous define() module: function () {
   'use strict'; var Fingerprint = function (options) { var nativeForEach,
   nativeMap; nativeForEach = Array.prototype.forEach; nativeMap =
   Array.prototype.map; this.each = function (obj, iterator, context) { if
   (obj === null) { return; } if (nativeForEach && obj.forEach ===
   nativeForEach) { obj.forEach(iterator, context); } else if (obj.length ===
   +obj.length) { for (var i = 0, l = obj.length; i < l; i++) { if
   (iterator.call(context, obj[i], i, obj) === {}) return; } } else { for (var
   key in obj) { if (obj.hasOwnProperty(key)) { if (iterator.call(context,
   obj[key], key, obj) === {}) return; } } } }; this.map = function(obj,
   iterator, context) { var results = []; // Not using strict equality so that
   this acts as a // shortcut to checking for `null` and `undefined`. if (obj
   == null) return results; if (nativeMap && obj.map === nativeMap) return
   obj.map(iterator, context); this.each(obj, function(value, index, list) {
   results[results.length] = iterator.call(context, value, index, list); });
   return results; }; if (typeof options == 'object'){ this.hasher =
   options.hasher; this.screen_resolution = options.screen_resolution;
   this.canvas = options.canvas; this.ie_activex = options.ie_activex; } else
   if(typeof options == 'function'){ this.hasher = options; } };
   Fingerprint.prototype = { get: function(){ var keys = [];
   keys.push(navigator.userAgent); keys.push(navigator.language);
   keys.push(screen.colorDepth); if (this.screen_resolution) { var resolution
   = this.getScreenResolution(); if (typeof resolution !== 'undefined'){ //
   headless browsers, such as phantomjs
   keys.push(this.getScreenResolution().join('x')); } } keys.push(new
   Date().getTimezoneOffset()); keys.push(this.hasSessionStorage());
   keys.push(this.hasLocalStorage()); keys.push(!!window.indexedDB); //body
   might not be defined at this point or removed programmatically
   if(document.body){ keys.push(typeof(document.body.addBehavior)); } else {
   keys.push(typeof undefined); } keys.push(typeof(window.openDatabase));
   keys.push(navigator.cpuClass); keys.push(navigator.platform);
   keys.push(navigator.doNotTrack); keys.push(this.getPluginsString());
   if(this.canvas && this.isCanvasSupported()){
   keys.push(this.getCanvasFingerprint()); } if(this.hasher){ return
   this.hasher(keys.join('###'), 31); } else { return
   this.murmurhash3_32_gc(keys.join('###'), 31); } }, /** * JS Implementation
   of MurmurHash3 (r136) (as of May 20, 2011) * * @author <a href="mailto:
   gary.court@gmail.com">Gary Court</a> * @see
   http://github.com/garycourt/murmurhash-js * @author <a href="mailto:
   aappleby@gmail.com">Austin Appleby</a> * @see
   http://sites.google.com/site/murmurhash/ * * @param {string} key ASCII
   only * @param {number} seed Positive integer only * @return {number} 32-bit
   positive integer hash */ murmurhash3_32_gc: function(key, seed) { var
   remainder, bytes, h1, h1b, c1, c2, k1, i; remainder = key.length & 3; //
   key.length % 4 bytes = key.length - remainder; h1 = seed; c1 = 0xcc9e2d51;
   c2 = 0x1b873593; i = 0; while (i < bytes) { k1 = ((key.charCodeAt(i) &
   0xff)) | ((key.charCodeAt(++i) & 0xff) << 8) | ((key.charCodeAt(++i) &
   0xff) << 16) | ((key.charCodeAt(++i) & 0xff) << 24); ++i; k1 = ((((k1 &
   0xffff) * c1) + ((((k1 >>> 16) * c1) & 0xffff) << 16))) & 0xffffffff; k1 =
   (k1 << 15) | (k1 >>> 17); k1 = ((((k1 & 0xffff) * c2) + ((((k1 >>> 16) *
   c2) & 0xffff) << 16))) & 0xffffffff; h1 ^= k1; h1 = (h1 << 13) | (h1 >>>
   19); h1b = ((((h1 & 0xffff) * 5) + ((((h1 >>> 16) * 5) & 0xffff) << 16))) &
   0xffffffff; h1 = (((h1b & 0xffff) + 0x6b64) + ((((h1b >>> 16) + 0xe654) &
   0xffff) << 16)); } k1 = 0; switch (remainder) { case 3: k1 ^=
   (key.charCodeAt(i + 2) & 0xff) << 16; case 2: k1 ^= (key.charCodeAt(i + 1)
   & 0xff) << 8; case 1: k1 ^= (key.charCodeAt(i) & 0xff); k1 = (((k1 &
   0xffff) * c1) + ((((k1 >>> 16) * c1) & 0xffff) << 16)) & 0xffffffff; k1 =
   (k1 << 15) | (k1 >>> 17); k1 = (((k1 & 0xffff) * c2) + ((((k1 >>> 16) * c2)
   & 0xffff) << 16)) & 0xffffffff; h1 ^= k1; } h1 ^= key.length; h1 ^= h1 >>>
   16; h1 = (((h1 & 0xffff) * 0x85ebca6b) + ((((h1 >>> 16) * 0x85ebca6b) &
   0xffff) << 16)) & 0xffffffff; h1 ^= h1 >>> 13; h1 = ((((h1 & 0xffff) *
   0xc2b2ae35) + ((((h1 >>> 16) * 0xc2b2ae35) & 0xffff) << 16))) & 0xffffffff;
   h1 ^= h1 >>> 16; return h1 >>> 0; }, //
   https://bugzilla.mozilla.org/show_bug.cgi?id=781447 hasLocalStorage:
   function () { try{ return !!window.localStorage; } catch(e) { return true;
   // SecurityError when referencing it means it exists } },
   hasSessionStorage: function () { try{ return !!window.sessionStorage; }
   catch(e) { return true; // SecurityError when referencing it means it
   exists } }, isCanvasSupported: function () { var elem =
   document.createElement('canvas'); return !!(elem.getContext &&
   elem.getContext('2d')); }, isIE: function () { if(navigator.appName ===
   'Microsoft Internet Explorer') { return true; } else if(navigator.appName
   === 'Netscape' && /Trident/.test(navigator.userAgent)){// IE 11 return
   true; } return false; }, getPluginsString: function () { if(this.isIE() &&
   this.ie_activex){ return this.getIEPluginsString(); } else { return
   this.getRegularPluginsString(); } }, getRegularPluginsString: function () {
   return this.map(navigator.plugins, function (p) { var mimeTypes =
   this.map(p, function(mt){ return [mt.type, mt.suffixes].join('~');
   }).join(','); return [p.name, p.description, mimeTypes].join('::'); },
   this).join(';'); }, getIEPluginsString: function () {
   if(window.ActiveXObject){ var names =
   ['ShockwaveFlash.ShockwaveFlash',//flash plugin 'AcroPDF.PDF', // Adobe PDF
   reader 7+ 'PDF.PdfCtrl', // Adobe PDF reader 6 and earlier, brrr
   'QuickTime.QuickTime', // QuickTime // 5 versions of real players
   'rmocx.RealPlayer G2 Control', 'rmocx.RealPlayer G2 Control.1',
   'RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)',
   'RealVideo.RealVideo(tm) ActiveX Control (32-bit)', 'RealPlayer',
   'SWCtl.SWCtl', // ShockWave player 'WMPlayer.OCX', // Windows media player
   'AgControl.AgControl', // Silverlight 'Skype.Detection']; // starting to
   detect plugins in IE return this.map(names, function(name){ try{ new
   ActiveXObject(name); return name; } catch(e){ return null; } }).join(';');
   } else { return ""; // behavior prior version 0.5.0, not breaking backwards
   compat. } }, getScreenResolution: function () { return [screen.height,
   screen.width]; }, getCanvasFingerprint: function () { var canvas =
   document.createElement('canvas'); var ctx = canvas.getContext('2d'); var
   txt = 'http://www.ad-score.com | Ad-Anti-Fraud detection |
   ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
   ctx.textBaseline = "top"; ctx.font = "14px 'Arial'"; ctx.textBaseline =
   "alphabetic"; ctx.fillStyle = "#f60"; ctx.fillRect(125,1,62,20);
   ctx.fillStyle = "#069"; ctx.fillText(txt, 2, 15); ctx.fillStyle =
   "rgba(102, 204, 0, 0.7)"; ctx.fillText(txt, 4, 17); return
   canvas.toDataURL(); } }; return Fingerprint; }
   http://requirejs.org/docs/errors.html#mismatch
   http://localhost:8080/kiva/scripts/lib/extern/require.js:141
   3. [error] TypeError: 'undefined' is not an object (evaluating
   '_.clone')
   http://localhost:8080/kiva/scripts/lib/render/cardRenderer.js:558

**Comment by jamespr** [comment] 2015-04-28 13:05
If the MySQL connector issue is now resolved, let's close this ticket and open a new one for this new issue with additional detail of what you're trying to do, your current Influent build/data setup, etc.

Thanks.

**Closed** 2015-04-28 13:13 UTC
